# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Catalyst-Authentication-Credential-Kerberos
version:      0.01
version_from: lib/Catalyst/Authentication/Credential/Kerberos.pm
installdirs:  site
requires:
    Authen::Krb5::Simple:          0
    Carp:                          0
    Catalyst::Authentication::Credential::Password: 0
    Catalyst::Exception:           0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
